<?php

/**
 * Abstract WP Hotel Booking widget class.
 *
 * @class       WPHB_Abstract_Widget
 * @version     2.0
 * @package     WP_Hotel_Booking/Classes
 * @category    Abstract Class
 * @author      Thimpress, leehld
 */

/**
 * Prevent loading this file directly
 */
defined( 'ABSPATH' ) || exit;

if ( ! class_exists( 'WPHB_Abstract_Widget' ) ) {

	/**
	 * Class WPHB_Abstract_Widget.
	 *
	 * @since 2.0
	 */
	abstract class WPHB_Abstract_Widget extends WP_Widget {

		/**
		 * @var string
		 */
		protected $widget_id = null;

		/**
		 * @var string
		 */
		public $widget_title = null;

		/**
		 * @var string
		 */
		public $widget_class;

		/**
		 * @var string
		 */
		public $widget_description;

		/**
		 * WPHB_Widget constructor.
		 *
		 * @since 2.0
		 */
		public function __construct() {
			$widget_ops = array(
				'classname'                   => $this->widget_class,
				'description'                 => $this->widget_description,
				'customize_selective_refresh' => true
			);
			parent::__construct( $this->widget_id, $this->widget_title, $widget_ops );
		}

		/**
		 * Display the widget content.
		 *
		 * @since 2.0
		 *
		 * @param array $args
		 * @param array $instance
		 */
		public function widget( $args, $instance ) {
			parent::widget( $args, $instance ); // TODO: Change the autogenerated stub
		}

		/**
		 * Outputs the settings update form.
		 *
		 * @since 2.0
		 *
		 * @param array $instance
		 *
		 * @return string
		 */
		public function form( $instance ) {
			return parent::form( $instance ); // TODO: Change the autogenerated stub
		}

		/**
		 *  Updates a particular instance of a widget.
		 *
		 * @since 2.0
		 *
		 * @param array $new_instance
		 * @param array $old_instance
		 *
		 * @return array
		 */
		public function update( $new_instance, $old_instance ) {
			return parent::update( $new_instance, $old_instance ); // TODO: Change the autogenerated stub
		}
	}
}